### ISSUE TITLE
Want to contribute Hackerrank Questions

### ISSUE THREAD

**Issue by ksalokya** [kanak22/CP-DSA-Questions#1]
Hey there, I just participated in Hackerrank Basic/Intermediate certification and passed successfully. Can I add those questions?

**Comment by kanak22** [comment]
yes you can add but you have to make a folder named HackerRank and inside it make another folder named Certification Questions..then make another folder inside the certification one by the name of the Certicfication.. This is to ensure the directory structure.

After this you have to make a separate file for each question with the question name and you can add them 🤗. 

let me know if you want to contribute ;)

**Comment by kanak22** [comment]
I am making a contributing.md i will push that most probably by morning ..have a look at that and then all of you can contribute ;)

**Comment by ksalokya** [comment]
> yes you can add but you have to make a folder named HackerRank and inside it make another folder named Certification Questions..then make another folder inside the certification one by the name of the Certicfication.. This is to ensure the directory structure.
> 
> After this you have to make a separate file for each question with the question name and you can add them 🤗.
> 
> let me know if you want to contribute ;)

yeah sure! will also add some of my leetcode questions.

**Comment by Himanshu-Agg12** [comment]
I want to add Some Hacker rank Java problems and solutions.

**Comment by kanak22** [comment]
Hey Folks, Read the contributing.md and then open issues for specific questions ;).. get them assigned and start working 🎉
