### ISSUE TITLE
Leetcode: Convert BST to Greater Tree

### ISSUE THREAD

**Issue by atish-90** [kanak22/CP-DSA-Questions#104]
## Link of the question
https://leetcode.com/problems/convert-bst-to-greater-tree/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by atish-90** [comment]
I would like to contribute the C++ solution for this problem.

**Comment by shalyavarnika** [comment]
I would like to contribute on any platform, preferably C++, Java or Python.

**Comment by kanak22** [comment]
edit and Mention the coding platform in title asap

**Comment by yashg41** [comment]
@kanak22 I want to do this question in Java
