### ISSUE TITLE
Find The Median- HackerRank

### ISSUE THREAD

**Issue by gunjan-g** [kanak22/CP-DSA-Questions#133]
## Link of the question
https://www.hackerrank.com/challenges/find-the-median/problem
I'm a participant in Hacktoberfest'21
Please assign this issue to me in C++

## Coding platform

- [x] Hackerrank

## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

## Additional context (OPTIONAL)
I'll add comments in my code for better understanding

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by kanak22** [comment]
hey @navjotdadwal in which language u would like to do this?

**Comment by navjotdadwal** [comment]
C++

**Comment by kanak22** [comment]
@navjotdadwal Its done in C++. Any other language you would like to contribute in?

**Comment by Yash0605** [comment]
@kanak22 can you please assign this issue to me I would like to solve this in python?
