### ISSUE TITLE
Ugly Number-LeetCode

### ISSUE THREAD

**Issue by Tishasoumya-02** [kanak22/CP-DSA-Questions#16]
## Link of the question
Link to the question-https://leetcode.com/problems/ugly-number/ .
Can I work on this question?

 I would like to provide in cpp

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by 2000shivam659** [comment]
Please assign me this issue under Hacktoberfest'21.
**Programing Language**

- [ ] Java

**Comment by Tishasoumya-02** [comment]
Can I work on this @kanak22, I issued this earlier to be able to work on this for Hacktoberfest

**Comment by kanak22** [comment]
Go Ahead ;)
