### ISSUE TITLE
Sort Colors - Leetcode

### ISSUE THREAD

**Issue by Piyushjar** [kanak22/CP-DSA-Questions#164]
## Link of the question
Provide the link of the question and ask for assignment of the issue.

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by kanak22** [comment]
hey @Piyushjar I wont be merging this PR as the issue hadnt been assigned to you and you made a pull request which breaches the guidelines of the project. So I m closing it

**Comment by kanak22** [comment]
If you wish to contribute, do follow all the guidelines and let me know then only I will assign this to you
