### ISSUE TITLE
Largest Rectangle in Histogram-LeetCode

### ISSUE THREAD

**Issue by Himanshu-Agg12** [kanak22/CP-DSA-Questions#17]
I want to do this task myself.

## Link of the question
[https://leetcode.com/problems/largest-rectangle-in-histogram/](
https://leetcode.com/problems/largest-rectangle-in-histogram/)

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

**Comment by 19-ade** [comment]
Hello . Can you assign me this ? I have computed the code in python.

**Comment by kanak22** [comment]
Go Ahead ;)
