### ISSUE TITLE
Top K frequent words - Leetcode

### ISSUE THREAD

**Issue by samridhikapoor** [kanak22/CP-DSA-Questions#234]
## Link of the question
https://leetcode.com/problems/top-k-frequent-words/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by samridhikapoor** [comment]
@kanak22 Please assign this issue to me under hacktoberfest '21. I would be contributing the code in C++ Language.
Thanks

**Comment by samridhikapoor** [comment]
@kanak I have created a PR for this issue. Kindly review the same.

Link to the PR: https://github.com/kanak22/CP-DSA-Questions/pull/284

Thanks

**Comment by kanak22** [comment]
Hey @samridhikapoor just do that change I suggested as it is becoming hectic day by day to rename all the files by myself ;) I hope you understand

**Comment by Abhishekgaikwadcoder** [comment]
@kanak22 Please assign this issue to me under hacktoberfest '21. I would be contributing the code in Java Language.
Thanks
