### ISSUE TITLE
 GUESS NUMBER HIGHER OR LOWER  Leet code    

### ISSUE THREAD

**Issue by vipul-2003** [kanak22/CP-DSA-Questions#25]
## Link of the question

[GUESS NUMBER HIGHER OR LOWER](https://leetcode.com/problems/guess-number-higher-or-lower/description/)

Provide the link of the question and ask for assignment of the issue.

Hi, I am participating at hacktober fest 2021 , and wanted to contribute to this issue ....

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by vipul-2003** [comment]
Please assign to me

**Comment by kanak22** [comment]
Only I am handling the repo 😊.. will assign you shortly .. :)
