### ISSUE TITLE
Spiral of a matrix in C++

### ISSUE THREAD

**Issue by SaloniJain24** [kanak22/CP-DSA-Questions#261]
## Link of the question
https://github.com/kanak22/CP-DSA-Questions/issues/122
## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [ ] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by SaloniJain24** [comment]
pls assign this problem to me under hacktoberfest'21

**Comment by kanak22** [comment]
Comment this under that issue and the PR you made before getting it assigned will not be merged as it breaches the guidelines of the project.

**Comment by SaloniJain24** [comment]
heyy @kanak22 , can u pls tell me exactly what i have to do as i am a beginner.

**Comment by kanak22** [comment]
@SaloniJain24 give a read to the contributing.md and readme of the project and then open an issue, wait for it to get assigned, after getting assigned start working on it and then make a PR ;)
