### ISSUE TITLE
Rotting Oranges Leetcode Problem 994

### ISSUE THREAD

**Issue by neenad99** [kanak22/CP-DSA-Questions#264]
## Link of the question
https://leetcode.com/problems/rotting-oranges/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by bsen20** [comment]
@kanak22  Please assign this one to me I will do it in C++.

**Comment by neenad99** [comment]
@kanak22  assign this issue to me for hacktoberfest

**Comment by kanak22** [comment]
@neenad99 will do this in C++, @bsen20 would like to do this in any other language?

**Comment by bsen20** [comment]
@kanak22 I'll do in java

**Comment by satyam-mahajan** [comment]
I would like to work on this issue, requesting you to please assign this issue to me. I will do in C++.
Thank you

**Comment by kanak22** [comment]
@satyam-mahajan cpp is done. Is there any language you can contribute in?

**Comment by satyam-mahajan** [comment]
@kanak22 I can do in Python also. Please assign

**Comment by kanak22** [comment]
Okay go ahead ;)

**Comment by poo17nam** [comment]
Do you want a solution in Javascript?

**Comment by kanak22** [comment]
yes :)

**Comment by poo17nam** [comment]
Hey @kanak22 I've raised a PR for JS solution. Let me know if I've missed anything :)
https://github.com/kanak22/CP-DSA-Questions/pull/397
