### ISSUE TITLE
Median of two sorted arrays - Leetcode

### ISSUE THREAD

**Issue by Devansh-gaur-1611** [kanak22/CP-DSA-Questions#319]
## Link of the question
https://leetcode.com/problems/median-of-two-sorted-arrays/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

## Additional context (OPTIONAL)
Hi, I want to work on this issue and submit it in the java language

**Comment by kanak22** [comment]
@Devansh-gaur-1611 comment here nd do not create duplicate issues ;) 

https://github.com/kanak22/CP-DSA-Questions/issues/243

**Comment by Devansh-gaur-1611** [comment]
Hi @kanak22, I am so sorry as I don't know that this issue had already been opened by someone else.

**Comment by kanak22** [comment]
Its okay @Devansh-gaur-1611 Just comment in that issue I will assign it to you. it is open for Java
