### ISSUE TITLE
3Sum - LeetCode

### ISSUE THREAD

**Issue by Amitdutta7** [kanak22/CP-DSA-Questions#320]
## Link of the question
https://leetcode.com/problems/3sum/
Hey, I would like to solve this Leetcode Problem No. 15 using C++. Kindly assign it to me. Thanks :)

## Coding platform
- [x] Leetcode

## Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

## Additional context (OPTIONAL)
I'll add some comments in my code for better understanding.

**Comment by Pratixingh** [comment]
https://leetcode.com/problems/clumsy-factorial/
I would like to solve  Leetcode Problem No. 1006 using C++. Please assign it to me.

**Comment by Devansh-gaur-1611** [comment]
Hello @kanak22 di, I want to do it in Java. Please assign it to me for java language

**Comment by kanak22** [comment]
@brilam @Devansh-gaur-1611 Go Ahead :) and @Pratixingh C++ is done

**Comment by Devansh-gaur-1611** [comment]
Hello @kanak22 di, what should be the file name for this problem
