### ISSUE TITLE
Prepbytes Question

### ISSUE THREAD

**Issue by mohitchandak** [kanak22/CP-DSA-Questions#349]
## Link of the question
Provide the link of the question and ask for assignment of the issue.

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [ ] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by mohitchandak** [comment]
having presbyters solution

**Comment by kanak22** [comment]
which language?

**Comment by Akhilesh0947** [comment]
please assign me any problem in c++

**Comment by Akhilesh0947** [comment]
please assign me [https://codeforces.com/contest/1562/problem/D1](url) this

**Comment by mohitchandak** [comment]
Bhout jaldi dediya tune access 🙂🙃

**Comment by kanak22** [comment]
@mohitchandak excuse me? that is not a way to talk I guess

**Comment by kanak22** [comment]
@Akhilesh0947
