### ISSUE TITLE
Find the Duplicate Number

### ISSUE THREAD

**Issue by AryaChakraborty** [kanak22/CP-DSA-Questions#35]
## Link of the question
https://leetcode.com/problems/find-the-duplicate-number/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by AryaChakraborty** [comment]
I would like to work on this in cpp.

**Comment by kanak22** [comment]
Mention the name of the platform in issue title

**Comment by Swapna804** [comment]
I would like to work on this issue

**Comment by kanak22** [comment]
In which language @Swapna804

**Comment by Swapna804** [comment]
in c++

**Comment by kanak22** [comment]
Cpp is already taken
