### ISSUE TITLE
House Robber

### ISSUE THREAD

**Issue by sarthakvijay** [kanak22/CP-DSA-Questions#379]
## Link of the question
https://leetcode.com/problems/house-robber/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

## Additional context (OPTIONAL)
Dynamic Programming problem

**Comment by kanak22** [comment]
It is already present
