### ISSUE TITLE
Inherited Code -Hackerrrank

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [kanak22/CP-DSA-Questions#41]
## Link of the question
Provide the link of the question and ask for assignment of the issue.
https://www.hackerrank.com/challenges/inherited-code/problem

## Coding platform

- [x] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [ ] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

## Additional context (OPTIONAL)
i want to work under hacktoberfest fest  kindly assign it to me

**Comment by kanak22** [comment]
Mention the platform name in title of issue
