### ISSUE TITLE
Working on extra long factorials-Hackerank

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [kanak22/CP-DSA-Questions#42]
## Link of the question
Provide the link of the question and ask for assignment of the issue.
https://www.hackerrank.com/challenges/extra-long-factorials/problem

## Coding platform

- [x] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [ ] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [x] Python

## Additional context (OPTIONAL)
I want to contribute in this context kindly assign it to me under hacktoberfest '21

**Comment by debjitpal5040** [comment]
I would like to solve this problem in python. Please assign me
