### ISSUE TITLE
Reversing the array -450 algo

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [kanak22/CP-DSA-Questions#43]
## Link of the question
Provide the link of the question and ask for assignment of the issue.
https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [ ] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [x] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

## Additional context (OPTIONAL)
I want to contribute under hacktoberfest'21 .Kindly assign it to me

**Comment by kanak22** [comment]
Correct algo to DSA in title

**Comment by kanak22** [comment]
Complete the other 3 issues assigned to you first

**Comment by cp-Coder** [comment]
Pls assign this task to me.

**Comment by kanak22** [comment]
In which language?

**Comment by cp-Coder** [comment]
C++

**Comment by sgaurav37533** [comment]
please assign me this issue in java language

**Comment by Himanshu664** [comment]
I have created PR please review.

**Comment by imishi450** [comment]
please assign me this task.

**Comment by Sri-vishnu-r1431** [comment]
I have created the pull request kindly assign this to me

**Comment by Sri-vishnu-r1431** [comment]
Manager kindly do so please

**Comment by kanak22** [comment]
Folks all the PRs related to this issue will be closed as it wasn't assigned to any one of you and making a PR without being assigned is a breach of the guidelines. 

And kindly have some patience and only make the PR's when you will get the issue assigned !
