### ISSUE TITLE
Remove Outermost Parentheses - LeetCode

### ISSUE THREAD

**Issue by silicolicious** [kanak22/CP-DSA-Questions#438]
## Link of the question
Provide the link of the question and ask for assignment of the issue.
Question - https://leetcode.com/problems/remove-outermost-parentheses/

## Coding platform
- [x] Leetcode

## Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

@kanak22 Please assign it to me

**Comment by tancot85** [comment]
Can i get this to solve?
