### ISSUE TITLE
Merge Sorted Array-LeetCode 

### ISSUE THREAD

**Issue by anubhav217** [kanak22/CP-DSA-Questions#574]
## Link of the question
Provide the link of the question and ask for assignment of the issue.

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [ ] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

**Comment by Sxmxrth** [comment]
Hello Kanak, can you please assign this issue to me in Java?

**Comment by Navaneethp007** [comment]
Hello Kanak,can you please assign this issue to me in C
