### ISSUE TITLE
Graph Coloring - Leet Code

### ISSUE THREAD

**Issue by manognyaa** [kanak22/CP-DSA-Questions#58]
## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [x] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

## Additional context (OPTIONAL)
Ugly numbers are numbers whose only prime factors are 2, 3 or 5. The sequence 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, … shows the first 11 ugly numbers. By convention, 1 is included. 

Given a number n, the task is to find nth Ugly number.

##Aim - our aim is to find nth ugly number.

Sir, pls assign me this issue to me @kanak22 sir. I am intrstd.

**Comment by kanak22** [comment]
ma'am*

**Comment by kanak22** [comment]
Instead of hacktoberfest'21 mention the coding platform in issue title, edit it.

**Comment by manognyaa** [comment]
> Instead of hacktoberfest'21 mention the coding platform in issue title, edit it.

Yes mam. sure !!! Thank you
