### ISSUE TITLE
Matrix Diagonal Sum - LeetCode

### ISSUE THREAD

**Issue by silicolicious** [kanak22/CP-DSA-Questions#9]
## Link of the question
https://leetcode.com/problems/matrix-diagonal-sum/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder

## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by silicolicious** [comment]
Hi!
I am a participant of Hacktoberfest and I would like to contribute to the above-mentioned question from LeetCode in the language C++
Assign me this issue.
Thank you!

**Comment by kanak22** [comment]
sure :)

**Comment by silicolicious** [comment]
> sure :)

When will the hacktoberfest label be added to the issue?

**Comment by kanak22** [comment]
by tomorrow

**Comment by silicolicious** [comment]
@kanak22 You assigned this issue to me, someone else is making PR for this :(

Please only accept mine.
