### ISSUE TITLE
Leetcode: Integer to Roman

### ISSUE THREAD

**Issue by atish-90** [kanak22/CP-DSA-Questions#98]
## Link of the question
https://leetcode.com/problems/integer-to-roman/

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Comment by atish-90** [comment]
I would like to work on this problem.

**Comment by atish-90** [comment]
Please assign it to me.

**Comment by kanak22** [comment]
edit and Mention the coding platform in title asap
